---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
implicit:
  - Корзина будет хранится в сессии браузера
  - При выборе языка, (Русский, English) сайт должен полностью изменить язык, на выбранный (Категории, Производитель, Описание товара)
  - Должна присутствовать регистрация аккаунта с добавлением способов оплаты, адресов доставок, сохранением корзины
  - При добавлении товаров в корзину, пользователь должен иметь возможность выбрать количество товаров
  - При оформлении заказа, должна быть возможность выбрать необходимые товары для заказа из корзины
